openapi: 3.0.3
info:
  title: 爱宠家宠物社区小程序 API
  version: 1.0.0
servers:
  - url: https://api.paw.example.com/api/v1
paths:
  /auth/code2session:
    post:
      summary: 微信code2Session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
              required: [code]
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Code2SessionResp'
  /auth/login/sms:
    post:
      summary: 短信验证码登录
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                code:
                  type: string
              required: [phone, code]
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResp'
  /auth/sms/send:
    post:
      summary: 发送短信验证码
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
              required: [phone]
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
  /users/me:
    get:
      summary: 获取当前用户信息
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    patch:
      summary: 更新当前用户信息
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: 成功
  /pets:
    get:
      summary: 我的宠物列表
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      summary: 新增宠物信息
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetCreate'
      responses:
        '200':
          description: 成功
  /posts:
    get:
      summary: 帖子列表
      parameters:
        - in: query
          name: page
          schema: { type: integer, default: 1 }
        - in: query
          name: pageSize
          schema: { type: integer, default: 20 }
        - in: query
          name: keyword
          schema: { type: string }
        - in: query
          name: tag
          schema: { type: string }
        - in: query
          name: petType
          schema: { type: string }
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostListResp'
    post:
      summary: 发布帖子
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostCreate'
      responses:
        '200':
          description: 成功
  /posts/{id}:
    get:
      summary: 帖子详情
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
    delete:
      summary: 删除帖子
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: 成功
  /posts/{id}/like:
    post:
      summary: 点赞帖子
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: 成功
    delete:
      summary: 取消点赞
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: 成功
  /comments:
    post:
      summary: 发表评论
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentCreate'
      responses:
        '200':
          description: 成功
  /dm/conversations:
    get:
      summary: 私信会话列表
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'
    post:
      summary: 创建会话
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                peerId:
                  type: integer
              required: [peerId]
      responses:
        '200':
          description: 成功
  /dm/messages:
    post:
      summary: 发送私信
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DMMessageCreate'
      responses:
        '200':
          description: 成功
  /products:
    get:
      summary: 商品列表
      parameters:
        - in: query
          name: categoryId
          schema: { type: integer }
        - in: query
          name: keyword
          schema: { type: string }
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListResp'
  /products/{id}:
    get:
      summary: 商品详情
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /cart:
    get:
      summary: 购物车详情
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
    post:
      summary: 添加商品到购物车
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartAddItem'
      responses:
        '200':
          description: 成功
  /orders:
    get:
      summary: 订单列表
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      summary: 创建订单
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreate'
      responses:
        '200':
          description: 成功
  /services/appointments:
    get:
      summary: 服务预约列表
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
    post:
      summary: 创建预约
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentCreate'
      responses:
        '200':
          description: 成功

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Code2SessionResp:
      type: object
      properties:
        openid:
          type: string
        session_key:
          type: string
        unionid:
          type: string
        token:
          type: string
    LoginResp:
      type: object
      properties:
        token:
          type: string
    User:
      type: object
      properties:
        id: { type: integer }
        nickname: { type: string }
        avatarUrl: { type: string }
        phone: { type: string }
    UserUpdate:
      type: object
      properties:
        nickname: { type: string }
        avatarUrl: { type: string }
    Pet:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }
        breed: { type: string }
        age: { type: integer }
        gender: { type: integer }
        avatarUrl: { type: string }
    PetCreate:
      type: object
      properties:
        name: { type: string }
        breed: { type: string }
        age: { type: integer }
        gender: { type: integer }
        avatarUrl: { type: string }
      required: [name]
    Post:
      type: object
      properties:
        id: { type: integer }
        userId: { type: integer }
        title: { type: string }
        content: { type: string }
        petType: { type: string }
        likeCount: { type: integer }
        commentCount: { type: integer }
        favoriteCount: { type: integer }
        createdAt: { type: string, format: date-time }
    PostCreate:
      type: object
      properties:
        title: { type: string }
        content: { type: string }
        petType: { type: string }
        media: { type: array, items: { $ref: '#/components/schemas/MediaItem' } }
      required: [content]
    MediaItem:
      type: object
      properties:
        type: { type: string, enum: [image, video] }
        url: { type: string }
    PostListResp:
      type: object
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/Post'
        page: { type: integer }
        pageSize: { type: integer }
        total: { type: integer }
    CommentCreate:
      type: object
      properties:
        postId: { type: integer }
        content: { type: string }
        parentId: { type: integer }
      required: [postId, content]
    Conversation:
      type: object
      properties:
        id: { type: integer }
        peerId: { type: integer }
        unread: { type: integer }
        lastMessage: { type: string }
    DMMessageCreate:
      type: object
      properties:
        conversationId: { type: integer }
        content: { type: string }
        mediaUrl: { type: string }
      required: [conversationId]
    Product:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }
        coverUrl: { type: string }
        description: { type: string }
    ProductListResp:
      type: object
      properties:
        list:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        total: { type: integer }
    Cart:
      type: object
      properties:
        id: { type: integer }
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
    CartItem:
      type: object
      properties:
        skuId: { type: integer }
        quantity: { type: integer }
        price: { type: number }
    CartAddItem:
      type: object
      properties:
        skuId: { type: integer }
        quantity: { type: integer }
      required: [skuId, quantity]
    Order:
      type: object
      properties:
        id: { type: integer }
        status: { type: string }
        totalAmount: { type: number }
        payAmount: { type: number }
    OrderCreate:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              skuId: { type: integer }
              quantity: { type: integer }
            required: [skuId, quantity]
        addressId: { type: integer }
      required: [items]
    Appointment:
      type: object
      properties:
        id: { type: integer }
        orgId: { type: integer }
        serviceItemId: { type: integer }
        scheduleId: { type: integer }
        status: { type: string }
    AppointmentCreate:
      type: object
      properties:
        orgId: { type: integer }
        serviceItemId: { type: integer }
        scheduleId: { type: integer }
      required: [orgId, serviceItemId, scheduleId]
