/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#586566",
        "on-tertiary": "#ffffff",
        "background": "#f4fafe",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#663e00",
        "surface-dim": "#d5dbdf",
        "primary-fixed-dim": "#ffb68c",
        "surface-container-high": "#e4eaee",
        "primary": "#944a00",
        "secondary-fixed-dim": "#cfdedf",
        "surface-bright": "#f4fafe",
        "on-secondary-fixed": "#161e1e",
        "on-surface": "#161c20",
        "inverse-on-surface": "#ebf1f6",
        "surface": "#f4fafe",
        "on-surface-variant": "#564337",
        "surface-variant": "#f4dcca",
        "on-primary-fixed-variant": "#713700",
        "inverse-primary": "#ffb68c",
        "on-error-container": "#410002",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#dde3e7",
        "tertiary": "#6e5d00",
        "on-background": "#161c20",
        "on-primary-container": "#301400",
        "on-tertiary-fixed": "#231b00",
        "on-tertiary-container": "#241e00",
        "secondary-fixed": "#ebfafb",
        "outline-variant": "#dcc1b1",
        "primary-container": "#ffdcbe",
        "error-container": "#ffdad6",
        "secondary": "#637475",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#e7c349",
        "surface-container": "#eef4f8",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#ffdcbe",
        "secondary-container": "#e7f8f9",
        "tertiary-container": "#ffe480",
        "on-secondary-fixed-variant": "#4a5b5c",
        "tertiary-fixed": "#ffe480",
        "outline": "#897365",
        "surface-container-low": "#f4fafe",
        "inverse-surface": "#2b3135"
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', '"Noto Sans SC"', 'sans-serif'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
