create table if not exists public.connection_test (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  note text not null default 'ok'
);

alter table public.connection_test enable row level security;
