create extension if not exists pgcrypto;

do $$ begin
  create type public.post_visibility as enum ('public', 'followers', 'private');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.post_status as enum ('draft', 'pending', 'approved', 'rejected');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.media_type as enum ('image', 'video');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.order_status as enum ('pending_pay', 'shipping', 'done', 'closed');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.payment_status as enum ('pending', 'paid', 'failed', 'refunded');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.refund_status as enum ('pending', 'processing', 'succeeded', 'failed');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.home_access_level as enum ('all', 'followers', 'self');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.comment_access_level as enum ('all', 'followers', 'disabled');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.appointment_status as enum ('pending', 'confirmed', 'canceled', 'done');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.service_order_status as enum ('pending_pay', 'paid', 'done', 'closed');
exception
  when duplicate_object then null;
end $$;

do $$ begin
  create type public.wallet_tx_type as enum ('recharge', 'consume', 'refund', 'adjust');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  openid text unique,
  unionid text,
  phone text unique,
  email text,
  nickname text not null,
  avatar_url text,
  location text,
  signature text,
  gender text,
  birthday date,
  status smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  role_id uuid not null references public.roles (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, role_id)
);

create table if not exists public.user_settings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles (id) on delete cascade,
  push_notice boolean not null default true,
  interact_notice boolean not null default true,
  home_access public.home_access_level not null default 'followers',
  comment_access public.comment_access_level not null default 'all',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pets (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles (id) on delete cascade,
  name text not null,
  avatar_url text,
  type text,
  breed text,
  gender text,
  weight_kg numeric(6,2),
  is_sterilized boolean,
  birthday date,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_pets_owner on public.pets (owner_id);

create table if not exists public.follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references public.profiles (id) on delete cascade,
  followee_id uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (follower_id, followee_id),
  check (follower_id <> followee_id)
);

create index if not exists idx_follows_follower on public.follows (follower_id);
create index if not exists idx_follows_followee on public.follows (followee_id);

create table if not exists public.topics (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles (id) on delete cascade,
  title text,
  content text not null,
  pet_type text,
  visibility public.post_visibility not null default 'public',
  status public.post_status not null default 'approved',
  location_name text,
  location_address text,
  like_count int not null default 0,
  comment_count int not null default 0,
  favorite_count int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index if not exists idx_posts_author_created on public.posts (author_id, created_at desc);
create index if not exists idx_posts_created on public.posts (created_at desc);
create index if not exists idx_posts_visibility_status on public.posts (visibility, status);

create table if not exists public.post_media (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  type public.media_type not null,
  url text not null,
  cover_url text,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_post_media_post on public.post_media (post_id);

create table if not exists public.post_tags (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  tag_id bigint not null references public.tags (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, tag_id)
);

create table if not exists public.post_topics (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  topic_id bigint not null references public.topics (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (post_id, topic_id)
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts (id) on delete cascade,
  author_id uuid not null references public.profiles (id) on delete cascade,
  parent_id bigint references public.comments (id) on delete set null,
  content text not null,
  like_count int not null default 0,
  status smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_comments_post_created on public.comments (post_id, created_at desc);
create index if not exists idx_comments_author on public.comments (author_id);

create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  post_id bigint not null references public.posts (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, post_id)
);

create index if not exists idx_post_likes_post on public.post_likes (post_id);

create table if not exists public.post_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  post_id bigint not null references public.posts (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, post_id)
);

create index if not exists idx_post_favorites_post on public.post_favorites (post_id);

create table if not exists public.comment_likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  comment_id bigint not null references public.comments (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, comment_id)
);

create index if not exists idx_comment_likes_comment on public.comment_likes (comment_id);

create table if not exists public.histories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  item_type text not null,
  item_id text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_histories_user_created on public.histories (user_id, created_at desc);

create table if not exists public.dm_conversations (
  id bigint generated by default as identity primary key,
  user_a uuid not null references public.profiles (id) on delete cascade,
  user_b uuid not null references public.profiles (id) on delete cascade,
  last_message_id bigint,
  unread_a int not null default 0,
  unread_b int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_a, user_b),
  check (user_a <> user_b)
);

create index if not exists idx_dm_conversations_user_a on public.dm_conversations (user_a);
create index if not exists idx_dm_conversations_user_b on public.dm_conversations (user_b);

create table if not exists public.dm_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.dm_conversations (id) on delete cascade,
  sender_id uuid not null references public.profiles (id) on delete cascade,
  content text,
  media_url text,
  created_at timestamptz not null default now()
);

create index if not exists idx_dm_messages_conv_created on public.dm_messages (conversation_id, created_at desc);
create index if not exists idx_dm_messages_sender on public.dm_messages (sender_id);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  type text not null,
  ref_type text,
  ref_id text,
  status smallint not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_notifications_user_created on public.notifications (user_id, created_at desc);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.categories (id) on delete set null,
  name text not null,
  sort_order int not null default 0
);

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories (id) on delete restrict,
  brand_id bigint references public.brands (id) on delete set null,
  code text unique,
  name text not null,
  description text,
  cover_url text,
  status smallint not null default 1,
  sold_count int not null default 0,
  rating numeric(3,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_products_category on public.products (category_id);
create index if not exists idx_products_status on public.products (status);

create table if not exists public.skus (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products (id) on delete cascade,
  spec text not null,
  price numeric(10,2) not null,
  market_price numeric(10,2),
  stock int not null default 0,
  status smallint not null default 1,
  unique (product_id, spec)
);

create index if not exists idx_skus_product on public.skus (product_id);

create table if not exists public.product_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.carts (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles (id) on delete cascade,
  updated_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint not null references public.carts (id) on delete cascade,
  sku_id bigint not null references public.skus (id) on delete restrict,
  quantity int not null,
  checked boolean not null default true,
  invalid boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (cart_id, sku_id)
);

create index if not exists idx_cart_items_cart on public.cart_items (cart_id);

create table if not exists public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  receiver text not null,
  phone text not null,
  province text,
  city text,
  district text,
  detail text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_addresses_user on public.addresses (user_id);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_no text not null unique,
  buyer_id uuid not null references public.profiles (id) on delete cascade,
  status public.order_status not null,
  total_amount numeric(10,2) not null,
  pay_amount numeric(10,2) not null,
  pay_method text,
  address_id bigint references public.addresses (id) on delete set null,
  address_snapshot jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_orders_buyer_created on public.orders (buyer_id, created_at desc);
create index if not exists idx_orders_status on public.orders (status);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders (id) on delete cascade,
  sku_id bigint not null references public.skus (id) on delete restrict,
  product_id bigint references public.products (id) on delete set null,
  product_name text,
  sku_spec text,
  price numeric(10,2) not null,
  quantity int not null
);

create index if not exists idx_order_items_order on public.order_items (order_id);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders (id) on delete cascade,
  status public.payment_status not null,
  transaction_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.refunds (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders (id) on delete cascade,
  status public.refund_status not null,
  amount numeric(10,2) not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_refunds_order on public.refunds (order_id);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  product_id bigint not null references public.products (id) on delete cascade,
  order_id bigint references public.orders (id) on delete set null,
  rating smallint not null,
  content text,
  status smallint not null default 1,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create index if not exists idx_reviews_product_created on public.reviews (product_id, created_at desc);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text unique not null,
  name text not null,
  discount numeric(10,2) not null,
  threshold numeric(10,2) not null default 0,
  start_at timestamptz not null,
  end_at timestamptz not null,
  total int,
  claimed int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.coupon_claims (
  id bigint generated by default as identity primary key,
  coupon_id bigint not null references public.coupons (id) on delete cascade,
  user_id uuid not null references public.profiles (id) on delete cascade,
  status smallint not null default 0,
  created_at timestamptz not null default now(),
  unique (coupon_id, user_id)
);

create index if not exists idx_coupon_claims_user on public.coupon_claims (user_id);

create table if not exists public.wallet_accounts (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles (id) on delete cascade,
  balance numeric(12,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.wallet_accounts (id) on delete cascade,
  tx_type public.wallet_tx_type not null,
  amount numeric(12,2) not null,
  ref_type text,
  ref_id text,
  created_at timestamptz not null default now()
);

create index if not exists idx_wallet_transactions_account_created on public.wallet_transactions (account_id, created_at desc);

create table if not exists public.recharge_options (
  id bigint generated by default as identity primary key,
  code text unique,
  amount numeric(12,2) not null,
  bonus numeric(12,2) not null default 0,
  status smallint not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.faqs (
  id bigint generated by default as identity primary key,
  q text not null,
  a text not null,
  weight int not null default 1,
  status smallint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.service_orgs (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  phone text,
  geo_lat numeric(10,6),
  geo_lng numeric(10,6),
  status smallint not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.service_types (
  id bigint generated by default as identity primary key,
  code text unique not null,
  name text not null
);

create table if not exists public.service_items (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.service_orgs (id) on delete cascade,
  type_code text not null references public.service_types (code) on delete restrict,
  name text not null,
  price numeric(10,2) not null,
  duration_min int not null,
  status smallint not null default 1
);

create index if not exists idx_service_items_org on public.service_items (org_id);
create index if not exists idx_service_items_type on public.service_items (type_code);

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  org_id bigint not null references public.service_orgs (id) on delete cascade,
  service_item_id bigint not null references public.service_items (id) on delete cascade,
  start_time timestamptz not null,
  end_time timestamptz not null,
  capacity int not null,
  reserved int not null default 0,
  status smallint not null default 1
);

create index if not exists idx_schedules_org_time on public.schedules (org_id, start_time);
create index if not exists idx_schedules_item_time on public.schedules (service_item_id, start_time);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  org_id bigint not null references public.service_orgs (id) on delete restrict,
  service_item_id bigint not null references public.service_items (id) on delete restrict,
  schedule_id bigint not null references public.schedules (id) on delete restrict,
  status public.appointment_status not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_appointments_user_created on public.appointments (user_id, created_at desc);

create table if not exists public.service_orders (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null unique references public.appointments (id) on delete cascade,
  amount numeric(10,2) not null,
  status public.service_order_status not null,
  created_at timestamptz not null default now()
);

create table if not exists public.service_records (
  id bigint generated by default as identity primary key,
  appointment_id bigint not null unique references public.appointments (id) on delete cascade,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  ref_type text not null,
  ref_id text not null,
  score smallint not null,
  content text,
  created_at timestamptz not null default now(),
  unique (user_id, ref_type, ref_id)
);

create table if not exists public.config_kv (
  id bigint generated by default as identity primary key,
  k text unique not null,
  v text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.banner_slots (
  id bigint generated by default as identity primary key,
  code text unique not null,
  name text not null,
  description text
);

create table if not exists public.banner_items (
  id bigint generated by default as identity primary key,
  slot_code text not null references public.banner_slots (code) on delete cascade,
  image_url text not null,
  title text,
  sub_title text,
  cta_text text,
  link_url text,
  badge text,
  bg_color text,
  border_radius int not null default 40,
  shadow_offset_x int not null default 12,
  shadow_offset_y int not null default 12,
  weight int not null default 1,
  status smallint not null default 1,
  start_at timestamptz,
  end_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_banner_items_slot on public.banner_items (slot_code);
create index if not exists idx_banner_items_time on public.banner_items (start_at, end_at);

create table if not exists public.community_cards (
  id bigint generated by default as identity primary key,
  image_url text not null,
  title text not null,
  link_url text,
  badge text,
  weight int not null default 1,
  status smallint not null default 1,
  start_at timestamptz,
  end_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_community_cards_time on public.community_cards (start_at, end_at);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles (id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.risk_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles (id) on delete set null,
  type text not null,
  detail text,
  created_at timestamptz not null default now()
);

create table if not exists public.ban_list (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  reason text,
  start_at timestamptz,
  end_at timestamptz
);

alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.user_roles enable row level security;
alter table public.user_settings enable row level security;
alter table public.pets enable row level security;
alter table public.follows enable row level security;
alter table public.topics enable row level security;
alter table public.tags enable row level security;
alter table public.posts enable row level security;
alter table public.post_media enable row level security;
alter table public.post_tags enable row level security;
alter table public.post_topics enable row level security;
alter table public.comments enable row level security;
alter table public.post_likes enable row level security;
alter table public.post_favorites enable row level security;
alter table public.comment_likes enable row level security;
alter table public.histories enable row level security;
alter table public.dm_conversations enable row level security;
alter table public.dm_messages enable row level security;
alter table public.notifications enable row level security;
alter table public.categories enable row level security;
alter table public.brands enable row level security;
alter table public.products enable row level security;
alter table public.skus enable row level security;
alter table public.product_favorites enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.addresses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.payments enable row level security;
alter table public.refunds enable row level security;
alter table public.reviews enable row level security;
alter table public.coupons enable row level security;
alter table public.coupon_claims enable row level security;
alter table public.wallet_accounts enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.recharge_options enable row level security;
alter table public.faqs enable row level security;
alter table public.service_orgs enable row level security;
alter table public.service_types enable row level security;
alter table public.service_items enable row level security;
alter table public.schedules enable row level security;
alter table public.appointments enable row level security;
alter table public.service_orders enable row level security;
alter table public.service_records enable row level security;
alter table public.ratings enable row level security;
alter table public.config_kv enable row level security;
alter table public.banner_slots enable row level security;
alter table public.banner_items enable row level security;
alter table public.community_cards enable row level security;
alter table public.audit_logs enable row level security;
alter table public.risk_events enable row level security;
alter table public.ban_list enable row level security;

drop policy if exists profiles_select_public on public.profiles;
create policy profiles_select_public on public.profiles
  for select to anon, authenticated
  using (true);

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles
  for insert to authenticated
  with check (auth.uid() = id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles
  for update to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists user_settings_select_own on public.user_settings;
create policy user_settings_select_own on public.user_settings
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists user_settings_upsert_own on public.user_settings;
create policy user_settings_upsert_own on public.user_settings
  for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists user_settings_update_own on public.user_settings;
create policy user_settings_update_own on public.user_settings
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists pets_select_own on public.pets;
create policy pets_select_own on public.pets
  for select to authenticated
  using (auth.uid() = owner_id and deleted_at is null);

drop policy if exists pets_insert_own on public.pets;
create policy pets_insert_own on public.pets
  for insert to authenticated
  with check (auth.uid() = owner_id);

drop policy if exists pets_update_own on public.pets;
create policy pets_update_own on public.pets
  for update to authenticated
  using (auth.uid() = owner_id)
  with check (auth.uid() = owner_id);

drop policy if exists pets_delete_own on public.pets;
create policy pets_delete_own on public.pets
  for delete to authenticated
  using (auth.uid() = owner_id);

drop policy if exists follows_select_public on public.follows;
create policy follows_select_public on public.follows
  for select to anon, authenticated
  using (true);

drop policy if exists follows_insert_own on public.follows;
create policy follows_insert_own on public.follows
  for insert to authenticated
  with check (auth.uid() = follower_id);

drop policy if exists follows_delete_own on public.follows;
create policy follows_delete_own on public.follows
  for delete to authenticated
  using (auth.uid() = follower_id);

drop policy if exists tags_select_public on public.tags;
create policy tags_select_public on public.tags
  for select to anon, authenticated
  using (true);

drop policy if exists topics_select_public on public.topics;
create policy topics_select_public on public.topics
  for select to anon, authenticated
  using (true);

drop policy if exists posts_select_public on public.posts;
create policy posts_select_public on public.posts
  for select to anon, authenticated
  using (
    deleted_at is null
    and (
      (visibility = 'public' and status = 'approved')
      or (author_id = auth.uid())
      or (
        visibility = 'followers'
        and status = 'approved'
        and (
          author_id = auth.uid()
          or exists (
            select 1
            from public.follows f
            where f.followee_id = posts.author_id
              and f.follower_id = auth.uid()
          )
        )
      )
    )
  );

drop policy if exists posts_insert_own on public.posts;
create policy posts_insert_own on public.posts
  for insert to authenticated
  with check (auth.uid() = author_id);

drop policy if exists posts_update_own on public.posts;
create policy posts_update_own on public.posts
  for update to authenticated
  using (auth.uid() = author_id)
  with check (auth.uid() = author_id);

drop policy if exists posts_delete_own on public.posts;
create policy posts_delete_own on public.posts
  for delete to authenticated
  using (auth.uid() = author_id);

drop policy if exists post_media_select_by_post on public.post_media;
create policy post_media_select_by_post on public.post_media
  for select to anon, authenticated
  using (
    exists (
      select 1
      from public.posts p
      where p.id = post_media.post_id
        and p.deleted_at is null
        and (
          (p.visibility = 'public' and p.status = 'approved')
          or (p.author_id = auth.uid())
          or (
            p.visibility = 'followers'
            and p.status = 'approved'
            and (
              p.author_id = auth.uid()
              or exists (
                select 1
                from public.follows f
                where f.followee_id = p.author_id
                  and f.follower_id = auth.uid()
              )
            )
          )
        )
    )
  );

drop policy if exists post_media_write_own on public.post_media;
create policy post_media_write_own on public.post_media
  for all to authenticated
  using (
    exists (
      select 1
      from public.posts p
      where p.id = post_media.post_id
        and p.author_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.posts p
      where p.id = post_media.post_id
        and p.author_id = auth.uid()
    )
  );

drop policy if exists post_tags_select_public on public.post_tags;
create policy post_tags_select_public on public.post_tags
  for select to anon, authenticated
  using (true);

drop policy if exists post_topics_select_public on public.post_topics;
create policy post_topics_select_public on public.post_topics
  for select to anon, authenticated
  using (true);

drop policy if exists comments_select_by_post on public.comments;
create policy comments_select_by_post on public.comments
  for select to anon, authenticated
  using (
    exists (
      select 1
      from public.posts p
      where p.id = comments.post_id
        and p.deleted_at is null
        and (
          (p.visibility = 'public' and p.status = 'approved')
          or (p.author_id = auth.uid())
          or (
            p.visibility = 'followers'
            and p.status = 'approved'
            and (
              p.author_id = auth.uid()
              or exists (
                select 1
                from public.follows f
                where f.followee_id = p.author_id
                  and f.follower_id = auth.uid()
              )
            )
          )
        )
    )
  );

drop policy if exists comments_insert_auth on public.comments;
create policy comments_insert_auth on public.comments
  for insert to authenticated
  with check (
    auth.uid() = author_id
    and exists (select 1 from public.posts p where p.id = comments.post_id and p.deleted_at is null)
  );

drop policy if exists comments_update_own on public.comments;
create policy comments_update_own on public.comments
  for update to authenticated
  using (auth.uid() = author_id)
  with check (auth.uid() = author_id);

drop policy if exists comments_delete_own on public.comments;
create policy comments_delete_own on public.comments
  for delete to authenticated
  using (auth.uid() = author_id);

drop policy if exists post_likes_select_own on public.post_likes;
create policy post_likes_select_own on public.post_likes
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists post_likes_write_own on public.post_likes;
create policy post_likes_write_own on public.post_likes
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists post_favorites_select_own on public.post_favorites;
create policy post_favorites_select_own on public.post_favorites
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists post_favorites_write_own on public.post_favorites;
create policy post_favorites_write_own on public.post_favorites
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists comment_likes_select_own on public.comment_likes;
create policy comment_likes_select_own on public.comment_likes
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists comment_likes_write_own on public.comment_likes;
create policy comment_likes_write_own on public.comment_likes
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists histories_select_own on public.histories;
create policy histories_select_own on public.histories
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists histories_write_own on public.histories;
create policy histories_write_own on public.histories
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists dm_conversations_select_participant on public.dm_conversations;
create policy dm_conversations_select_participant on public.dm_conversations
  for select to authenticated
  using (auth.uid() = user_a or auth.uid() = user_b);

drop policy if exists dm_conversations_write_participant on public.dm_conversations;
create policy dm_conversations_write_participant on public.dm_conversations
  for all to authenticated
  using (auth.uid() = user_a or auth.uid() = user_b)
  with check (auth.uid() = user_a or auth.uid() = user_b);

drop policy if exists dm_messages_select_participant on public.dm_messages;
create policy dm_messages_select_participant on public.dm_messages
  for select to authenticated
  using (
    exists (
      select 1
      from public.dm_conversations c
      where c.id = dm_messages.conversation_id
        and (auth.uid() = c.user_a or auth.uid() = c.user_b)
    )
  );

drop policy if exists dm_messages_insert_sender on public.dm_messages;
create policy dm_messages_insert_sender on public.dm_messages
  for insert to authenticated
  with check (
    auth.uid() = sender_id
    and exists (
      select 1
      from public.dm_conversations c
      where c.id = dm_messages.conversation_id
        and (auth.uid() = c.user_a or auth.uid() = c.user_b)
    )
  );

drop policy if exists notifications_select_own on public.notifications;
create policy notifications_select_own on public.notifications
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists categories_select_public on public.categories;
create policy categories_select_public on public.categories
  for select to anon, authenticated
  using (true);

drop policy if exists brands_select_public on public.brands;
create policy brands_select_public on public.brands
  for select to anon, authenticated
  using (true);

drop policy if exists products_select_public on public.products;
create policy products_select_public on public.products
  for select to anon, authenticated
  using (status = 1);

drop policy if exists skus_select_public on public.skus;
create policy skus_select_public on public.skus
  for select to anon, authenticated
  using (status = 1);

drop policy if exists product_favorites_select_own on public.product_favorites;
create policy product_favorites_select_own on public.product_favorites
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists product_favorites_write_own on public.product_favorites;
create policy product_favorites_write_own on public.product_favorites
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists carts_select_own on public.carts;
create policy carts_select_own on public.carts
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists carts_write_own on public.carts;
create policy carts_write_own on public.carts
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists cart_items_select_own on public.cart_items;
create policy cart_items_select_own on public.cart_items
  for select to authenticated
  using (
    exists (
      select 1
      from public.carts c
      where c.id = cart_items.cart_id
        and c.user_id = auth.uid()
    )
  );

drop policy if exists cart_items_write_own on public.cart_items;
create policy cart_items_write_own on public.cart_items
  for all to authenticated
  using (
    exists (
      select 1
      from public.carts c
      where c.id = cart_items.cart_id
        and c.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.carts c
      where c.id = cart_items.cart_id
        and c.user_id = auth.uid()
    )
  );

drop policy if exists addresses_select_own on public.addresses;
create policy addresses_select_own on public.addresses
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists addresses_write_own on public.addresses;
create policy addresses_write_own on public.addresses
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists orders_select_own on public.orders;
create policy orders_select_own on public.orders
  for select to authenticated
  using (auth.uid() = buyer_id);

drop policy if exists orders_write_own on public.orders;
create policy orders_write_own on public.orders
  for all to authenticated
  using (auth.uid() = buyer_id)
  with check (auth.uid() = buyer_id);

drop policy if exists order_items_select_own on public.order_items;
create policy order_items_select_own on public.order_items
  for select to authenticated
  using (
    exists (
      select 1
      from public.orders o
      where o.id = order_items.order_id
        and o.buyer_id = auth.uid()
    )
  );

drop policy if exists payments_select_own on public.payments;
create policy payments_select_own on public.payments
  for select to authenticated
  using (
    exists (
      select 1
      from public.orders o
      where o.id = payments.order_id
        and o.buyer_id = auth.uid()
    )
  );

drop policy if exists refunds_select_own on public.refunds;
create policy refunds_select_own on public.refunds
  for select to authenticated
  using (
    exists (
      select 1
      from public.orders o
      where o.id = refunds.order_id
        and o.buyer_id = auth.uid()
    )
  );

drop policy if exists reviews_select_public on public.reviews;
create policy reviews_select_public on public.reviews
  for select to anon, authenticated
  using (status = 1);

drop policy if exists reviews_insert_own on public.reviews;
create policy reviews_insert_own on public.reviews
  for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists reviews_update_own on public.reviews;
create policy reviews_update_own on public.reviews
  for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists coupons_select_public on public.coupons;
create policy coupons_select_public on public.coupons
  for select to anon, authenticated
  using (now() between start_at and end_at);

drop policy if exists coupon_claims_select_own on public.coupon_claims;
create policy coupon_claims_select_own on public.coupon_claims
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists coupon_claims_insert_own on public.coupon_claims;
create policy coupon_claims_insert_own on public.coupon_claims
  for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists wallet_accounts_select_own on public.wallet_accounts;
create policy wallet_accounts_select_own on public.wallet_accounts
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists wallet_accounts_write_own on public.wallet_accounts;
create policy wallet_accounts_write_own on public.wallet_accounts
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists wallet_transactions_select_own on public.wallet_transactions;
create policy wallet_transactions_select_own on public.wallet_transactions
  for select to authenticated
  using (
    exists (
      select 1
      from public.wallet_accounts a
      where a.id = wallet_transactions.account_id
        and a.user_id = auth.uid()
    )
  );

drop policy if exists recharge_options_select_public on public.recharge_options;
create policy recharge_options_select_public on public.recharge_options
  for select to anon, authenticated
  using (status = 1);

drop policy if exists faqs_select_public on public.faqs;
create policy faqs_select_public on public.faqs
  for select to anon, authenticated
  using (status = 1);

drop policy if exists service_orgs_select_public on public.service_orgs;
create policy service_orgs_select_public on public.service_orgs
  for select to anon, authenticated
  using (status = 1);

drop policy if exists service_types_select_public on public.service_types;
create policy service_types_select_public on public.service_types
  for select to anon, authenticated
  using (true);

drop policy if exists service_items_select_public on public.service_items;
create policy service_items_select_public on public.service_items
  for select to anon, authenticated
  using (status = 1);

drop policy if exists schedules_select_public on public.schedules;
create policy schedules_select_public on public.schedules
  for select to anon, authenticated
  using (status = 1);

drop policy if exists appointments_select_own on public.appointments;
create policy appointments_select_own on public.appointments
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists appointments_write_own on public.appointments;
create policy appointments_write_own on public.appointments
  for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists service_orders_select_own on public.service_orders;
create policy service_orders_select_own on public.service_orders
  for select to authenticated
  using (
    exists (
      select 1
      from public.appointments a
      where a.id = service_orders.appointment_id
        and a.user_id = auth.uid()
    )
  );

drop policy if exists service_records_select_own on public.service_records;
create policy service_records_select_own on public.service_records
  for select to authenticated
  using (
    exists (
      select 1
      from public.appointments a
      where a.id = service_records.appointment_id
        and a.user_id = auth.uid()
    )
  );

drop policy if exists ratings_select_public on public.ratings;
create policy ratings_select_public on public.ratings
  for select to anon, authenticated
  using (true);

drop policy if exists ratings_insert_own on public.ratings;
create policy ratings_insert_own on public.ratings
  for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists config_kv_select_public on public.config_kv;
create policy config_kv_select_public on public.config_kv
  for select to anon, authenticated
  using (true);

drop policy if exists banner_slots_select_public on public.banner_slots;
create policy banner_slots_select_public on public.banner_slots
  for select to anon, authenticated
  using (true);

drop policy if exists banner_items_select_public on public.banner_items;
create policy banner_items_select_public on public.banner_items
  for select to anon, authenticated
  using (
    status = 1
    and (start_at is null or start_at <= now())
    and (end_at is null or end_at >= now())
  );

drop policy if exists community_cards_select_public on public.community_cards;
create policy community_cards_select_public on public.community_cards
  for select to anon, authenticated
  using (
    status = 1
    and (start_at is null or start_at <= now())
    and (end_at is null or end_at >= now())
  );

grant usage on schema public to anon, authenticated;

grant select on table public.profiles to anon, authenticated;
grant insert, update on table public.profiles to authenticated;

grant select, insert, update, delete on table public.user_settings to authenticated;
grant select on table public.follows to anon, authenticated;
grant insert, delete on table public.follows to authenticated;
grant select, insert, update, delete on table public.pets to authenticated;
grant select on table public.tags to anon, authenticated;
grant select on table public.topics to anon, authenticated;

grant select on table public.posts to anon, authenticated;
grant insert, update, delete on table public.posts to authenticated;
grant select on table public.post_media to anon, authenticated;
grant insert, update, delete on table public.post_media to authenticated;
grant select on table public.post_tags to anon, authenticated;
grant select on table public.post_topics to anon, authenticated;
grant select on table public.comments to anon, authenticated;
grant insert, update, delete on table public.comments to authenticated;

grant select, insert, update, delete on table public.post_likes to authenticated;
grant select, insert, update, delete on table public.post_favorites to authenticated;
grant select, insert, update, delete on table public.comment_likes to authenticated;
grant select, insert, update, delete on table public.histories to authenticated;

grant select, insert, update, delete on table public.dm_conversations to authenticated;
grant select, insert, update, delete on table public.dm_messages to authenticated;
grant select, insert, update, delete on table public.notifications to authenticated;

grant select on table public.categories to anon, authenticated;
grant select on table public.brands to anon, authenticated;
grant select on table public.products to anon, authenticated;
grant select on table public.skus to anon, authenticated;
grant select, insert, update, delete on table public.product_favorites to authenticated;

grant select, insert, update, delete on table public.carts to authenticated;
grant select, insert, update, delete on table public.cart_items to authenticated;
grant select, insert, update, delete on table public.addresses to authenticated;

grant select, insert, update, delete on table public.orders to authenticated;
grant select, insert, update, delete on table public.order_items to authenticated;
grant select, insert, update, delete on table public.payments to authenticated;
grant select, insert, update, delete on table public.refunds to authenticated;
grant select, insert, update, delete on table public.reviews to anon, authenticated;

grant select on table public.coupons to anon, authenticated;
grant select, insert, update, delete on table public.coupon_claims to authenticated;
grant select, insert, update, delete on table public.wallet_accounts to authenticated;
grant select, insert, update, delete on table public.wallet_transactions to authenticated;
grant select on table public.recharge_options to anon, authenticated;
grant select on table public.faqs to anon, authenticated;

grant select on table public.service_orgs to anon, authenticated;
grant select on table public.service_types to anon, authenticated;
grant select on table public.service_items to anon, authenticated;
grant select on table public.schedules to anon, authenticated;
grant select, insert, update, delete on table public.appointments to authenticated;
grant select, insert, update, delete on table public.service_orders to authenticated;
grant select, insert, update, delete on table public.service_records to authenticated;
grant select, insert, update, delete on table public.ratings to anon, authenticated;

grant select on table public.config_kv to anon, authenticated;
grant select on table public.banner_slots to anon, authenticated;
grant select on table public.banner_items to anon, authenticated;
grant select on table public.community_cards to anon, authenticated;

grant usage, select on all sequences in schema public to anon, authenticated;
